apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog
  namespace: graylog
  labels:
    app: graylog
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
      tier: app
  template:
    metadata:
      labels:
        app: graylog
        tier: app
    spec:
      containers:
      - name: graylog
        image: graylog/graylog:4.2.7
        ports: 
          - name: web
            containerPort: 9000
          - name: syslog
            containerPort: 8514
          - name: gelf
            containerPort: 12201
        env:
          - name: GRAYLOG_PASSWORD_SECRET
            valueFrom:
              secretKeyRef:
                name: graylog-config
                key: GRAYLOG_PASSWORD_SECRET
          - name: GRAYLOG_ROOT_PASSWORD_SHA2
            valueFrom:
              secretKeyRef:
                name: graylog-config
                key: GRAYLOG_ROOT_PASSWORD_SHA2
          - name: GRAYLOG_SERVER_JAVA_OPTS 
            value: -Xmx150m -Xms150m
          - name: GRAYLOG_HTTP_BIND_ADDRESS
            value: 0.0.0.0:9000
          - name: GRAYLOG_HTTP_EXTERNAL_URI
            value: http://192.168.80.10:30100/
          - name: GRAYLOG_MONGODB_URI
            value:  mongodb://mongodb.graylog.svc.cluster.local/graylog
          - name: GRAYLOG_ELASTICSEARCH_HOSTS
            value: http://elasticsearch.graylog.svc.cluster.local:9200
        resources:
          limits:
            cpu: 700m
            memory: 700Mi
          requests:
            cpu: 700m
            memory: 700Mi
      #   volumeMounts:
      #   - name: graylog-mongodb-data
      #     mountPath: /data/db
      # volumes:
      # - name: graylog-mongodb-data
      #   persistentVolumeClaim:
      #     claimName: graylog-mongodb-pv-claim
---
apiVersion: v1
kind: Secret
metadata:
  name: graylog-config
  namespace: graylog
type: Opaque
stringData:
  GRAYLOG_PASSWORD_SECRET: "28567128511447726647"
  GRAYLOG_ROOT_PASSWORD_SHA2: "923d4e08b2bf7172067aa4c5795d68d29cf68639bc5940b21541bce99cc98c34"
---
apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: graylog
spec:
  type: NodePort
  selector:
    app: graylog
    tier: app
  ports:
    - name: web
      port: 9000
      targetPort: 9000
    - name: syslog
      port: 8514
      targetPort: 8514
    - name: gelf
      port: 12201
      targetPort: 12201
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: graylog-mongodb-pv
#   namespace: graylog
# spec:
#   accessModes:
#     - ReadWriteMany
#   capacity:
#     storage: 1Gi
#   nfs:
#     server: nfs-server
#     path: /nfs/system/graylog/mongodb
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: graylog-mongodb-pv-claim
#   namespace: graylog
# spec:
#   storageClassName: ""
#   accessModes:
#     - ReadWriteMany
#   resources:
#     requests:
#       storage: 1Gi