apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: graylog
  labels:
    app: graylog
    tier: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
      tier: db
  template:
    metadata:
      labels:
        app: graylog
        tier: db
    spec:
      containers:
      - name: mongodb
        image: mongo:5.0.6
        ports: 
          - containerPort: 27017
        resources:
          limits:
            cpu: 300m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 200Mi
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: graylog
spec:
  type: NodePort
  selector:
    app: graylog
    tier: db
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pvc
  namespace: graylog
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: graylog-mongodb-pv
  namespace: graylog
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    server: nfs-server
    path: /nfs/system/graylog/mongodb
