- name: Get resources manifest
  ansible.builtin.get_url:
    url: https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml
    dest: /tmp/metrics-server.yml
    mode: "0644"

- name: Apply resources manifest
  kubernetes.core.k8s:
    state: present
    src: /tmp/metrics-server.yml

- name: Remove resources manifest
  ansible.builtin.file:
    path: /tmp/metrics-server.yml
    state: absent
