apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  namespace: kibana
  labels:
    app: kibana
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kibana
      tier: app
  template:
    metadata:
      labels:
        app: kibana
        tier: app
    spec:
      containers:
      - name: kiban
        image: kibana:8.1.2
        ports: 
          - name: web
            containerPort: 5601
        env:
          - name: ES_JAVA_OPTS
            value: -Xmx150m -Xms150m
          - name: SERVER_HOST
            value: 0.0.0.0
          - name: ELASTICSEARCH_HOSTS
            value: "http://elasticsearch.kibana.svc.cluster.local:9200"
        resources:
          limits:
            cpu: 600m
            memory: 600Mi
          requests:
            cpu: 600m
            memory: 600Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: kibana
spec:
  type: NodePort
  selector:
    app: kibana
    tier: app
  ports:
    - name: web
      port: 5601
      targetPort: 5601