Vagrant.configure("2") do |config|
  
  config.vm.define "node-box" do |local|
    local.vm.box = "debian/bullseye64"
    local.vm.hostname = "node-box"
    local.ssh.insert_key = false

    local.vm.network "private_network", ip: "192.168.80.240"
    
    local.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end

    config.vm.provision "shell" do |shell|
      ssh_pub_key = File.readlines("#{ENV["WSL_HOME_DIR"]}\\.ssh\\id_ansible_kubernetes_cluster.pub").first.strip
      shell.inline = <<-SHELL
      echo #{ssh_pub_key} >> /home/vagrant/.ssh/authorized_keys
      SHELL
    end
  end
  
end
