apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
localAPIEndpoint:
  advertiseAddress: "192.168.80.10"
  bindPort: 6443
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
controlPlaneEndpoint: "192.168.80.10:6443"
networking:
  dnsDomain: "cluster.local"
  podSubnet: "172.16.0.0/16"
  serviceSubnet: "172.17.0.0/22"
---
apiVersion: kubelet.config.k8s.io/v1beta1
kind: KubeletConfiguration
serverTLSBootstrap: true
authentication:
  webhook:
    enabled: true
authorization:
  mode: "Webhook"