- name: Check for existing cert-manager controller pod
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Pod
    namespace: cert-manager
    label_selectors:
      - "app.kubernetes.io/component=controller"
      - "app.kubernetes.io/instance=cert-manager"
      - "app.kubernetes.io/name=cert-manager"
  register: certmanager_pod

- name: Install cert-manager
  ansible.builtin.include_tasks: "init.yml"
  when: certmanager_pod.resources | length == 0

- name: Configure CA resources
  ansible.builtin.include_tasks: "init_ca.yml"
  when: certmanager_pod.resources | length == 0
