- name: Check if kubelet is already configured
  ansible.builtin.stat:
    path: /etc/kubernetes/kubelet.conf
  become: true
  register: kubelet_conf

- name: Join the node
  ansible.builtin.include_tasks: "join.yml"
  when: not kubelet_conf.stat.exists
