- name: Get latest stable version
  ansible.builtin.shell: |
    CILIUM_CLI_VERSION=$(curl -s https://raw.githubusercontent.com/cilium/cilium-cli/master/stable.txt)
    echo $CILIUM_CLI_VERSION
  register: cilium_version
  changed_when: cilium_version.rc == 0

- name: Get binary archive (with checksum)
  ansible.builtin.get_url:
    url: "https://github.com/cilium/cilium-cli/releases/download/{{ cilium_version.stdout }}/cilium-linux-amd64.tar.gz"
    dest: /tmp/cilium-linux-amd64.tar.gz
    checksum: "sha256:https://github.com/cilium/cilium-cli/releases/download/{{ cilium_version.stdout }}/cilium-linux-amd64.tar.gz.sha256sum"
    mode: "0755"

- name: Extract binary from the archive
  ansible.builtin.unarchive:
    src: /tmp/cilium-linux-amd64.tar.gz
    dest: /usr/local/bin
    remote_src: true
    mode: "0755"
  become: true

- name: Remove binary archive
  ansible.builtin.file:
    path: /tmp/cilium-linux-amd64.tar.gz
    state: absent

- name: Install Cilium in the cluster
  ansible.builtin.shell: |
    cilium install
  register: cilium_install
  changed_when: cilium_install.rc == 0

- name: Display install output
  ansible.builtin.debug:
    var: cilium_install.stdout_lines
