apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-cluster-role
subjects:
  - kind: ServiceAccount
    name: fluent-bit-sa
    namespace: kube-system