# - name: Init control-plane
#   ansible.builtin.include_tasks: init_cluster.yml
#   when: operation is defined and operation == "init"

# - name: Add node to the control-plane
#   ansible.builtin.include_tasks: join_node.yml
#   when: operation is defined and operation == "join-node"

- name: Checking for existing etcd directory
  ansible.builtin.stat:
    path: /var/lib/etcd/
  become: true
  register: etcd_directory
  when: operation is defined

- name: Init control-plane
  ansible.builtin.include_tasks: "init/main.yml"
  when: (operation is defined and operation == "init") and not etcd_directory.stat.exists

- name: Join new control node
  ansible.builtin.include_tasks: "join/main.yml"
  when: (operation is defined and operation == "join-node") and not etcd_directory.stat.exists
