apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: worker-node-user
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: worker-node-user
subjects:
- kind: User
  name: worker-node
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: worker-node-user
  apiGroup: rbac.authorization.k8s.io