apiVersion: v1
kind: Secret
metadata:
  name: zabbix-postgres-config
  namespace: zabbix-server
type: Opaque
stringData:
  POSTGRES_USER: zabbix
  POSTGRES_PASSWORD: password
  POSTGRES_DB: zabbix
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zabbix-postgres-pv
  namespace: zabbix-server
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: nfs-server
    path: /nfs/system/zabbix/postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zabbix-postgres
  namespace: zabbix-server
spec:
  selector:
    matchLabels:
      app: zabbix
      tier: db
  serviceName: "postgres"
  replicas: 1
  template:
    metadata:
      labels:
        app: zabbix
        tier: db
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: postgres
        image: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: zabbix-postgres-config
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zabbix-postgres-config
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: zabbix-postgres-config
                key: POSTGRES_DB
        volumeMounts:
        - name: zabbix-postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: zabbix-postgres-data
    spec:
      volumeName: zabbix-postgres-pv
      accessModes: [ "ReadWriteMany" ]
      resources:
        requests:
          storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-postgres
  namespace: zabbix-server
spec:
  selector:
    app: zabbix
    tier: db
  ports:
    - port: 5432
      targetPort: 5432
