apiVersion: v1
kind: Secret
metadata:
  name: zabbix-web-tls
  namespace: zabbix-server
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUR5VENDQXJHZ0F3SUJBZ0lVRDhqUm9RTVVrbTNEWUY5WnA1aFFWc2VsU2h3d0RRWUpLb1pJaHZjTkFRRUwKQlFBd2RERUxNQWtHQTFVRUJoTUNSbEl4RXpBUkJnTlZCQWdNQ2xOdmJXVXRVM1JoZEdVeElUQWZCZ05WQkFvTQpHRWx1ZEdWeWJtVjBJRmRwWkdkcGRITWdVSFI1SUV4MFpERXRNQ3NHQTFVRUF3d2tlbUZpWW1sNExYZGxZaTVrClpXWmhkV3gwTG5OMll5NWpiSFZ6ZEdWeUxteHZZMkZzTUI0WERUSXlNREV6TURFeU1qTTFPVm9YRFRJek1ERXoKTURFeU1qTTFPVm93ZERFTE1Ba0dBMVVFQmhNQ1JsSXhFekFSQmdOVkJBZ01DbE52YldVdFUzUmhkR1V4SVRBZgpCZ05WQkFvTUdFbHVkR1Z5Ym1WMElGZHBaR2RwZEhNZ1VIUjVJRXgwWkRFdE1Dc0dBMVVFQXd3a2VtRmlZbWw0CkxYZGxZaTVrWldaaGRXeDBMbk4yWXk1amJIVnpkR1Z5TG14dlkyRnNNSUlCSWpBTkJna3Foa2lHOXcwQkFRRUYKQUFPQ0FROEFNSUlCQ2dLQ0FRRUF5ZXFxYkxBUFExdnZVbG81dHVjZ2tCbnJnUENNV0pKY1BZUm8vbE9HNmhwdwpDdWhYeUhXV1hJTGpkenBSVTFXR2VWTHlKaXFpbHREcEl0VGMyVm1XZURUWFJ1ZzRFTVJLNTJCTmtlb0luRWRFCk9SYUw5bU9IWmZiQ24zYWtJMXNoNWtwQVNWL2RrSTQ2cXppSG1oM1JjNVRMeDFlNUo2SnlWY0tvaFhiZW5HYWgKWVovZUwwOW9Hb0o3U1VEWmViR3JUbkh1M0pYR2pvVk9iM3liL25qMEJlUkZrcXJ1Z0l2Ti9SK0h6Q0E2anJUVApObEVwK3MvWnMwYWxLZ1VsNlljdzgyL1I3Umg2UEJkUEpqWmhaclphZkg5c1VTOWI0WDhOQURjbmRqeitISmZpCkRvRWpma1VGVU1BUis3QnRZUnEzVGV5L2lsTERWaFh3U3hDVlZSRXNOd0lEQVFBQm8xTXdVVEFkQmdOVkhRNEUKRmdRVWtZVlFvOXdUNlFQdk51VkhxclJCL2wrUjdEVXdId1lEVlIwakJCZ3dGb0FVa1lWUW85d1Q2UVB2TnVWSApxclJCL2wrUjdEVXdEd1lEVlIwVEFRSC9CQVV3QXdFQi96QU5CZ2txaGtpRzl3MEJBUXNGQUFPQ0FRRUFWUjRVCnhLNWpGcG1HQytMZWk1NGRtTisyTml4UmNINTU4M0dEV3QrOHlsM1B0NGNJc3VJTnM0ZW91bUMwbmMrVXVHMmgKK3JaVDg3eXJNc2Z3a2dzYmQ0YmN3TnNsQ3BUc0ZvaGtJbTdCYStYVmVrdURaZmpkRHRtREgzTmE2dFNFU0paVwo2eXg0M3B3Z01RQ3cyUDBoc1g1bVJ5dis3eCtiNDJzbWJicGhrTVU2bHJZOGFnNitDeExrTmxVbytLUUVXczJKCkJBN2R5K3dMM2hvMUhONXVWM2N4c1hxSE9lN3d2bk9kMStkTENRcm1kTjRoWHk0VFhpSTFzaG9pR0lhMnZqQmMKeklQMlB0TnQ1aDFYY3c2dWh0VkRNTmpPdTBxKzhVcEEvUVRUUlpySm9kZHg0bzFpZ3NBVnJVM0xSVTcvSGN4WgoxQ1h5UlpNUk8vdFFGN21GQVE9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRREo2cXBzc0E5RFcrOVMKV2ptMjV5Q1FHZXVBOEl4WWtsdzloR2orVTRicUduQUs2RmZJZFpaY2d1TjNPbEZUVllaNVV2SW1LcUtXME9raQoxTnpaV1paNE5OZEc2RGdReEVybllFMlI2Z2ljUjBRNUZvdjJZNGRsOXNLZmRxUWpXeUhtU2tCSlg5MlFqanFyCk9JZWFIZEZ6bE12SFY3a25vbkpWd3FpRmR0NmNacUZobjk0dlQyZ2FnbnRKUU5sNXNhdE9jZTdjbGNhT2hVNXYKZkp2K2VQUUY1RVdTcXU2QWk4MzlINGZNSURxT3ROTTJVU242ejltelJxVXFCU1hwaHpEemI5SHRHSG84RjA4bQpObUZtdGxwOGYyeFJMMXZoZncwQU55ZDJQUDRjbCtJT2dTTitSUVZRd0JIN3NHMWhHcmRON0wrS1VzTldGZkJMCkVKVlZFU3czQWdNQkFBRUNnZ0VBQ0JqRTVMN2FuZFRkNyt0MlRRTlBwdmVqSGZTSGJEWFNSUlUrTUpTZzRGcFgKQzlqdFREaUs0d0xNcEVkT1k0MFdhMThNSHNPdTZXVlBNL3BkTU1vSzRwOGIwdGdWQjNjWG1kZWV4SzhoMFVKNgpWZCsxbFJmQW9qSVc4OVlLRnZEY2x5TjdHSFlqcUZ4THRmbjZWZy9FQ21KNUdYRkhGM1BJS2ZBNFdjRytnMzczCnpwVU9WOWh3TXFyR0NTK0J1VCtyZmZUMVJ5aDBSTElqUzBTQk51WXlXYmU3dUx1VjZoUm1KdGF3eURCRTduNmsKbHkvZER1RHVQaURrRENuWGRUcTUzaDM3cWlyTDNWSUxPQXZCOWRXdlpoUzh6Wk5QUmVDbm5ndWw0M25ORS9UdgpUbHVHUFhmQ1BCVmpCMVlreVl5ek5xSGxPY0I0SHNsTUFWUS9FYk1rQVFLQmdRRHdYaS9kcVFpSjdkYkJYRk43Cm0vVmlXczBPYWNwNlp6YXhOWlNrbmhvZkdmZWZ3eGJOQ2RtUThpQWNEQWQ0OVo5Q0cvWUovNmxIc2xVck81NkQKMzRSZ1ZRNXV4WVRkVjJSUWtBUUJjZWNHUHZXaGE1Y0ZVTVBPWHRIQjVxaDQ4WlZDTFhhQ2J2L245MUg5VkNpVApBbHQ2aUhFYVhVM3JwaGlTbDBxVGtiaFZ0d0tCZ1FEWERGQzlhcnI2dE1KQjZ0UWxTeGRrRVpwdVJRbE94T0dEClgxVUZkaitKdWp4aXZ1UWtCMnV3ZEI4RS9mTFo0RzUvQURTR2xONWdPRnVqaFdhcmV5KzJiaFFRSlArODFWRWoKeWg2eWFDNUlrdHU2VG1aaFhDSys4NjhNQnRmZ0xNTXU4eFJQNm5LN2tBU1NjTjJRWGRLbFF6dGQ1MzhDbnhqQwpYYUxtVEVuZGdRS0JnQXZMazIyOUxiNFcvY0xmVlBscjNjN0Z4ZW8vSnNCNjhDUWlEUGxIQ09FZDFSang2ZHlGCjd6YzlxblcxNFdmK0phS0kzTG9BNGIyeThwcjhnZnJXclJoTkZEZzdXUm5EZ0JpeitINVpxSXlWNmxmUmY4ZXkKL3VqUm5sbDFpQzduSy92alh6MW5WUWQ5QzNqeStFcStndDZ3YzF4bjE3c0ltNHdXQUlMZFU3NWhBb0dCQUxZbApja1hlSHgyMitVc0g4a1RjUTZXNDIwdEhJa2ticmIrdWdiOHNsMGk2KytiUHRVRm5INm5IMFhaUyt0M2NvUHJsClc1Z2FnL2lRQTk2UFlaVWh0Qm9iUnRjZDM1YzhQNHZHNlJWSDlOdjN1REVuc3NRSVhFM003Wm1NT2xGZzJMbnQKbm1qS05mLzBUa3NUV2plcm9IM21ZbVI1YmpUME9PNTRqVC92b2lrQkFvR0JBTEdMSDBoeGFtWmZUa2hYcUR4ZgorWCtIVHl6RmFLdFRmUG15NzdqR2wxUmRGQVBSOVUwdmNySWQvRDNXbzk5UGNwRDFnNFVFWnVvSnFSd25GUU9GCnI3OHhJVEVjbVFkMHIyWFVHRW95dGp6dHdRYXl0eHpkd3plQkNWdHVRTDI3K3dFZ2o1YXBKNEJablBjQTFOVk8KbzdObEEraE5za0ljTWdhWmVMK1NMY3FqCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0=
type: kubernetes.io/tls
---
apiVersion: v1
kind: Secret
metadata:
  name: zabbix-web-config-postgres
  namespace: zabbix-server
type: Opaque
stringData:
  POSTGRES_USER: zabbix
  POSTGRES_PASSWORD: password
  POSTGRES_DB: zabbix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-web
  namespace: zabbix-server
  labels:
    app: zabbix
    tier: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix
      tier: web
  template:
    metadata:
      labels:
        app: zabbix
        tier: web
    spec:
      containers:
      - name: zabbix-web
        image: zabbix/zabbix-web-nginx-pgsql
        ports: 
          - name: web-http
            containerPort: 8080
        env:
          - name: ZBX_SERVER_HOST
            value: zabbix-server.zabbix-server.svc.cluster.local
          - name: DB_SERVER_HOST
            value: postgres.zabbix-server.svc.cluster.local
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: zabbix-web-config-postgres
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zabbix-web-config-postgres
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: zabbix-web-config-postgres
                key: POSTGRES_DB
          - name: PHP_TZ
            value: "Europe/Paris"
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-web
  namespace: zabbix-server
spec:
  selector:
    app: zabbix
    tier: web
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: zabbix-ingress
  namespace: zabbix-server
spec:
  ingressClassName: nginx
  rules:
  - host: k8s-zabbix
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: zabbix-web
            port:
              number: 8080
  tls:
    - hosts:
      - k8s-zabbix
      secretName: zabbix-web-tls
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: zabbix-web
  namespace: zabbix-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: zabbix-web
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
