apiVersion: v1
kind: Secret
metadata:
  name: zabbix-server-config-postgres
  namespace: zabbix-server
type: Opaque
stringData:
  POSTGRES_USER: zabbix
  POSTGRES_PASSWORD: password
  POSTGRES_DB: zabbix
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zabbix-server
  namespace: zabbix-server
  labels:
    app: zabbix
    tier: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zabbix
      tier: server
  template:
    metadata:
      labels:
        app: zabbix
        tier: server
    spec:
      containers:
      - name: zabbix-server
        image: zabbix/zabbix-server-pgsql
        ports: 
          - containerPort: 10051
        env:
          - name: DB_SERVER_HOST
            value: postgres.zabbix-server.svc.cluster.local
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: zabbix-server-config-postgres
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zabbix-server-config-postgres
                key: POSTGRES_PASSWORD
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: zabbix-server-config-postgres
                key: POSTGRES_DB
        resources:
          limits:
            cpu: "300m"
            memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: zabbix-server
  namespace: zabbix-server
spec:
  selector:
    app: zabbix
    tier: server
  ports:
    - port: 10051
      targetPort: 10051