- name: Generate kubeconfig config file
  ansible.builtin.blockinfile:
    path: /tmp/kubeadm-user-config.yaml
    create: true
    mode: "0644"
    block: |
      apiVersion: kubeadm.k8s.io/v1beta3
      kind: ClusterConfiguration
      clusterName: "kubernetes"
      controlPlaneEndpoint: "{{ control_plane_endpoint }}:6443"
      certificatesDir: "/etc/kubernetes/pki"

- name: Generate kubeconfig for worker node
  ansible.builtin.shell: |
    kubeadm kubeconfig user \
      --config /tmp/kubeadm-user-config.yaml \
      --client-name worker-node \
      > /tmp/kubeconfig-worker.conf
  register: worker_kubeconfig
  changed_when: worker_kubeconfig.rc == 0
  become: true

- name: Save worker kubeconfig
  ansible.builtin.fetch:
    src: /tmp/kubeconfig-worker.conf
    dest: "{{ role_path }}/files/kubeconfig-worker.conf"
    mode: "0644"
    flat: true
  become: true

- name: Remove kubeconfig file
  ansible.builtin.file:
    path: /tmp/kubeconfig-worker.conf
    state: absent
  become: true

- name: Remove kubeconfig config file
  ansible.builtin.file:
    path: /tmp/kubeadm-user-config.yaml
    state: absent

- name: Create a clusterRole for the worker kubeconfig user
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      metadata:
        name: worker-node-user
      rules:
        - apiGroups: ["*"]
          resources: ["*"]
          verbs: ["*"]

- name: Create a clusterRoleBinding for the worker kubeconfig user
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: worker-node-user
      subjects:
        - kind: User
          name: worker-node
          apiGroup: rbac.authorization.k8s.io
      roleRef:
        kind: ClusterRole
        name: worker-node-user
        apiGroup: rbac.authorization.k8s.io
