- name: Install packages
  ansible.builtin.package: # noqa : package-latest
    name:
      - nfs-kernel-server
    state: latest
  become: true

- name: Create nfs folders
  ansible.builtin.file:
    path: "{{ item.value }}"
    state: directory
    recurse: true
  become: true
  loop:
    - "/nfs/system/zabbix/postgres"

- name: Configure /etc/exports
  ansible.builtin.lineinfile:
    path: /etc/exports
    regexp: '^/nfs/ 192.168.80.0/24(rw,sync,no_subtree_check,no_root_squash)'
    line: '/nfs/ 192.168.80.0/24(rw,sync,no_subtree_check,no_root_squash)'
  become: true

- name: Set nfs folder permissions
  ansible.builtin.file:
    path: /nfs
    state: directory
    owner: nobody
    group: nogroup
    mode: "0770"
    recurse: true
  become: true

- name: Start nfs-kernel-server service
  ansible.builtin.systemd:
    state: started
    name: nfs-kernel-server
    enabled: true
  become: true
